# Generated by Django 5.2.7 on 2025-10-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_pelicula', models.CharField(max_length=200, verbose_name='Título de la película')),
                ('genero', models.CharField(max_length=100, verbose_name='Género')),
                ('duracion', models.PositiveIntegerField(verbose_name='Duración (minutos)')),
                ('clasificacion', models.CharField(max_length=20, verbose_name='Clasificación')),
                ('sinopsis', models.TextField(blank=True, verbose_name='Sinopsis')),
            ],
        ),
    ]
